title: <p align="center"> Michael Lin </p>

#logo: "/images/picture.png?raw=false"

description:
  <p align="center">
  <a href="pdf/Vinoth Updated Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinothnk/">LinkedIn</a> |
  <a href="https://github.com/vinothnk">GitHub</a>
  </p>
  
  <p align="justify">
  I am a masters student at SUSS Singapore. 
  <br><br>
  My area of interest is in data, the currency of this century.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-3YS8RW7EWH # Google Analytics tracking ID
